<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Lipa.BackBlaze.Client</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>9.0.1</Version>
		<Authors>Lipa</Authors>
		<Company>Lipa</Company>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/Aniluffi/Back-Blaze_Nuget.git</RepositoryUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Description>
			9.0.1 - добавлены методы для работы с файлами
			9.0.0 - добавлены методы для работы с файлами
			8.0.3 - Добавлен Readme.md.
			8.0.2 - Добавлены настройки .csproj.
			8.0.1 - Доработана для публикации в Nuget.
			8.0.0 - Библиотека для работы с BackBlaze B2 Cloud Storage.
		</Description>
	</PropertyGroup>

	<ItemGroup>
		<!-- Подключаем README.md из корня репозитория -->
		<None Include="..\..\README.md" Pack="true" PackagePath="" Link="README.md" />
	</ItemGroup>

	<PropertyGroup>
		<!-- Чтобы NuGet включал зависимости автоматически -->
		<IncludeSymbols>true</IncludeSymbols>
		<IncludeSource>true</IncludeSource>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.17" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.17" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.17" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.17" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Http.Client\Http.Client.csproj" />
	</ItemGroup>

</Project>
